//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evmsService.entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private string NameField;
        
        private evmsService.entities.Faculty UserFacultyField;
        
        private bool isEventOrganizerField;
        
        private bool isLocationAdminField;
        
        private bool isNormalUserField;
        
        private bool isSystemAdminField;
        
        private string userIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.Faculty UserFaculty
        {
            get
            {
                return this.UserFacultyField;
            }
            set
            {
                this.UserFacultyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isEventOrganizer
        {
            get
            {
                return this.isEventOrganizerField;
            }
            set
            {
                this.isEventOrganizerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isLocationAdmin
        {
            get
            {
                return this.isLocationAdminField;
            }
            set
            {
                this.isLocationAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isNormalUser
        {
            get
            {
                return this.isNormalUserField;
            }
            set
            {
                this.isNormalUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSystemAdmin
        {
            get
            {
                return this.isSystemAdminField;
            }
            set
            {
                this.isSystemAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Faculty", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public enum Faculty : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Science = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Engineering = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Arts_and_Social_Science = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Dentistry = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Law = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        School_of_Computing = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yong_Loo_Lin_School_of_Medicine = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yong_Siew_Toh_Conservatory_Of_Music = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        School_of_Design_and_Environment = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        School_of_Business = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Centre_for_Development_of_Teaching_and_Learning = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Centre_for_Instructional_Technology = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Computing_Commons = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Education_Resource_Centre = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EduSports = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Khoo_Teck_Puat_Advanced_Surgery_Training_Centre = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lee_Kuan_Yew_School_of_Public_Policy = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PC_Cluster = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Science_Cluster = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UTown = 19,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysRole", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class SysRole : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RemarksField;
        
        private int RoleLevelField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleLevel
        {
            get
            {
                return this.RoleLevelField;
            }
            set
            {
                this.RoleLevelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private System.DateTime EndDateTimeField;
        
        private string NameField;
        
        private evmsService.entities.User OrganizerField;
        
        private string OrganizeridField;
        
        private System.DateTime StartDateTimeField;
        
        private string WebsiteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDateTime
        {
            get
            {
                return this.EndDateTimeField;
            }
            set
            {
                this.EndDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.User Organizer
        {
            get
            {
                return this.OrganizerField;
            }
            set
            {
                this.OrganizerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organizerid
        {
            get
            {
                return this.OrganizeridField;
            }
            set
            {
                this.OrganizeridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDateTime
        {
            get
            {
                return this.StartDateTimeField;
            }
            set
            {
                this.StartDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website
        {
            get
            {
                return this.WebsiteField;
            }
            set
            {
                this.WebsiteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notifications", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class Notifications : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string ReceiverField;
        
        private System.DateTime SendDateTimeField;
        
        private string SenderField;
        
        private string TitleField;
        
        private bool isReadField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDateTime
        {
            get
            {
                return this.SendDateTimeField;
            }
            set
            {
                this.SendDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isRead
        {
            get
            {
                return this.isReadField;
            }
            set
            {
                this.isReadField = value;
            }
        }
    }
}
namespace evmsService.Controllers
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    public partial class SException : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEvmsService")]
public interface IEvmsService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/login", ReplyAction="http://tempuri.org/IEvmsService/loginResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/loginSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.User login(string userid, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignLocationAdmin", ReplyAction="http://tempuri.org/IEvmsService/assignLocationAdminResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/assignLocationAdminSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    bool assignLocationAdmin(evmsService.entities.User assigner, string userid, string description);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignEventOrganizer", ReplyAction="http://tempuri.org/IEvmsService/assignEventOrganizerResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/assignEventOrganizerSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    bool assignEventOrganizer(evmsService.entities.User assigner, string userid, string description);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignSystemAdmin", ReplyAction="http://tempuri.org/IEvmsService/assignSystemAdminResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/assignSystemAdminSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    bool assignSystemAdmin(evmsService.entities.User assigner, string userid, string description);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/searchUser", ReplyAction="http://tempuri.org/IEvmsService/searchUserResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/searchUserSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.User[] searchUser(string name, string userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/searchUserByRole", ReplyAction="http://tempuri.org/IEvmsService/searchUserByRoleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/searchUserByRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.User[] searchUserByRole(string name, string userid, int r);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/viewUserRole", ReplyAction="http://tempuri.org/IEvmsService/viewUserRoleResponse")]
    evmsService.entities.SysRole viewUserRole(string userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/unAssignRole", ReplyAction="http://tempuri.org/IEvmsService/unAssignRoleResponse")]
    bool unAssignRole(evmsService.entities.User assigner, string userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/CreateEvent", ReplyAction="http://tempuri.org/IEvmsService/CreateEventResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/CreateEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void CreateEvent(evmsService.entities.User u, string EventName, System.DateTime EventStartDateTime, System.DateTime EventEndDatetime, string EventDescription, string EventWebsite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/ViewEvent", ReplyAction="http://tempuri.org/IEvmsService/ViewEventResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/ViewEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Event[] ViewEvent(evmsService.entities.User u);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/EditEvent", ReplyAction="http://tempuri.org/IEvmsService/EditEventResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/EditEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void EditEvent(evmsService.entities.User u, evmsService.entities.Event e);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/DeleteEvent", ReplyAction="http://tempuri.org/IEvmsService/DeleteEventResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/DeleteEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void DeleteEvent(evmsService.entities.User u, evmsService.entities.Event e);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getNewMessage", ReplyAction="http://tempuri.org/IEvmsService/getNewMessageResponse")]
    string getNewMessage(string rid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getUnreadMessageCount", ReplyAction="http://tempuri.org/IEvmsService/getUnreadMessageCountResponse")]
    int getUnreadMessageCount(string rid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getUnreadMessages", ReplyAction="http://tempuri.org/IEvmsService/getUnreadMessagesResponse")]
    evmsService.entities.Notifications[] getUnreadMessages(string rid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getAllMessages", ReplyAction="http://tempuri.org/IEvmsService/getAllMessagesResponse")]
    evmsService.entities.Notifications[] getAllMessages(string rid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/deleteNotifications", ReplyAction="http://tempuri.org/IEvmsService/deleteNotificationsResponse")]
    void deleteNotifications(evmsService.entities.Notifications n);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/deleteAllNotificationsOfUser", ReplyAction="http://tempuri.org/IEvmsService/deleteAllNotificationsOfUserResponse")]
    void deleteAllNotificationsOfUser(string uid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/setNotificationRead", ReplyAction="http://tempuri.org/IEvmsService/setNotificationReadResponse")]
    void setNotificationRead(evmsService.entities.Notifications n);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/sendNotification", ReplyAction="http://tempuri.org/IEvmsService/sendNotificationResponse")]
    void sendNotification(string sender, string receiver, string title, string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/addFacility", ReplyAction="http://tempuri.org/IEvmsService/addFacilityResponse")]
    void addFacility(evmsService.entities.User u, string LocID, evmsService.entities.Faculty fac, string loc, string bookingCon, string techCon, int cap);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/removeFacility", ReplyAction="http://tempuri.org/IEvmsService/removeFacilityResponse")]
    void removeFacility(evmsService.entities.User u, string LocID, evmsService.entities.Faculty fac);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/updateFacility", ReplyAction="http://tempuri.org/IEvmsService/updateFacilityResponse")]
    void updateFacility(evmsService.entities.User u, string locID, evmsService.entities.Faculty fac, string loc, string bookingCon, string techCon, int cap);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEvmsServiceChannel : IEvmsService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EvmsServiceClient : System.ServiceModel.ClientBase<IEvmsService>, IEvmsService
{
    
    public EvmsServiceClient()
    {
    }
    
    public EvmsServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EvmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EvmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EvmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public evmsService.entities.User login(string userid, string password)
    {
        return base.Channel.login(userid, password);
    }
    
    public bool assignLocationAdmin(evmsService.entities.User assigner, string userid, string description)
    {
        return base.Channel.assignLocationAdmin(assigner, userid, description);
    }
    
    public bool assignEventOrganizer(evmsService.entities.User assigner, string userid, string description)
    {
        return base.Channel.assignEventOrganizer(assigner, userid, description);
    }
    
    public bool assignSystemAdmin(evmsService.entities.User assigner, string userid, string description)
    {
        return base.Channel.assignSystemAdmin(assigner, userid, description);
    }
    
    public evmsService.entities.User[] searchUser(string name, string userid)
    {
        return base.Channel.searchUser(name, userid);
    }
    
    public evmsService.entities.User[] searchUserByRole(string name, string userid, int r)
    {
        return base.Channel.searchUserByRole(name, userid, r);
    }
    
    public evmsService.entities.SysRole viewUserRole(string userid)
    {
        return base.Channel.viewUserRole(userid);
    }
    
    public bool unAssignRole(evmsService.entities.User assigner, string userid)
    {
        return base.Channel.unAssignRole(assigner, userid);
    }
    
    public void CreateEvent(evmsService.entities.User u, string EventName, System.DateTime EventStartDateTime, System.DateTime EventEndDatetime, string EventDescription, string EventWebsite)
    {
        base.Channel.CreateEvent(u, EventName, EventStartDateTime, EventEndDatetime, EventDescription, EventWebsite);
    }
    
    public evmsService.entities.Event[] ViewEvent(evmsService.entities.User u)
    {
        return base.Channel.ViewEvent(u);
    }
    
    public void EditEvent(evmsService.entities.User u, evmsService.entities.Event e)
    {
        base.Channel.EditEvent(u, e);
    }
    
    public void DeleteEvent(evmsService.entities.User u, evmsService.entities.Event e)
    {
        base.Channel.DeleteEvent(u, e);
    }
    
    public string getNewMessage(string rid)
    {
        return base.Channel.getNewMessage(rid);
    }
    
    public int getUnreadMessageCount(string rid)
    {
        return base.Channel.getUnreadMessageCount(rid);
    }
    
    public evmsService.entities.Notifications[] getUnreadMessages(string rid)
    {
        return base.Channel.getUnreadMessages(rid);
    }
    
    public evmsService.entities.Notifications[] getAllMessages(string rid)
    {
        return base.Channel.getAllMessages(rid);
    }
    
    public void deleteNotifications(evmsService.entities.Notifications n)
    {
        base.Channel.deleteNotifications(n);
    }
    
    public void deleteAllNotificationsOfUser(string uid)
    {
        base.Channel.deleteAllNotificationsOfUser(uid);
    }
    
    public void setNotificationRead(evmsService.entities.Notifications n)
    {
        base.Channel.setNotificationRead(n);
    }
    
    public void sendNotification(string sender, string receiver, string title, string msg)
    {
        base.Channel.sendNotification(sender, receiver, title, msg);
    }
    
    public void addFacility(evmsService.entities.User u, string LocID, evmsService.entities.Faculty fac, string loc, string bookingCon, string techCon, int cap)
    {
        base.Channel.addFacility(u, LocID, fac, loc, bookingCon, techCon, cap);
    }
    
    public void removeFacility(evmsService.entities.User u, string LocID, evmsService.entities.Faculty fac)
    {
        base.Channel.removeFacility(u, LocID, fac);
    }
    
    public void updateFacility(evmsService.entities.User u, string locID, evmsService.entities.Faculty fac, string loc, string bookingCon, string techCon, int cap)
    {
        base.Channel.updateFacility(u, locID, fac, loc, bookingCon, techCon, cap);
    }
}
