//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gems.UIWPF.evmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isEventOrganizerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isLocationAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isNormalUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSystemAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isEventOrganizer {
            get {
                return this.isEventOrganizerField;
            }
            set {
                if ((this.isEventOrganizerField.Equals(value) != true)) {
                    this.isEventOrganizerField = value;
                    this.RaisePropertyChanged("isEventOrganizer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isLocationAdmin {
            get {
                return this.isLocationAdminField;
            }
            set {
                if ((this.isLocationAdminField.Equals(value) != true)) {
                    this.isLocationAdminField = value;
                    this.RaisePropertyChanged("isLocationAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isNormalUser {
            get {
                return this.isNormalUserField;
            }
            set {
                if ((this.isNormalUserField.Equals(value) != true)) {
                    this.isNormalUserField = value;
                    this.RaisePropertyChanged("isNormalUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSystemAdmin {
            get {
                return this.isSystemAdminField;
            }
            set {
                if ((this.isSystemAdminField.Equals(value) != true)) {
                    this.isSystemAdminField = value;
                    this.RaisePropertyChanged("isSystemAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                if ((object.ReferenceEquals(this.userIDField, value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    [System.SerializableAttribute()]
    public partial class SException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysRole", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class SysRole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleLevel {
            get {
                return this.RoleLevelField;
            }
            set {
                if ((this.RoleLevelField.Equals(value) != true)) {
                    this.RoleLevelField = value;
                    this.RaisePropertyChanged("RoleLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Gems.UIWPF.evmsService.EventContact> EventContactListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Gems.UIWPF.evmsService.Guest> GuestListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Gems.UIWPF.evmsService.Item> ItemListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Gems.UIWPF.evmsService.ItemType> ItemTypeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Gems.UIWPF.evmsService.Location> LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Gems.UIWPF.evmsService.ManPower> ManPowerListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gems.UIWPF.evmsService.User OrganizerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Gems.UIWPF.evmsService.Participant> ParticipantListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Gems.UIWPF.evmsService.Program> ProgramsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Gems.UIWPF.evmsService.Task> TaskListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDateTime {
            get {
                return this.EndDateTimeField;
            }
            set {
                if ((this.EndDateTimeField.Equals(value) != true)) {
                    this.EndDateTimeField = value;
                    this.RaisePropertyChanged("EndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.EventContact> EventContactList {
            get {
                return this.EventContactListField;
            }
            set {
                if ((object.ReferenceEquals(this.EventContactListField, value) != true)) {
                    this.EventContactListField = value;
                    this.RaisePropertyChanged("EventContactList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.Guest> GuestList {
            get {
                return this.GuestListField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestListField, value) != true)) {
                    this.GuestListField = value;
                    this.RaisePropertyChanged("GuestList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.Item> ItemList {
            get {
                return this.ItemListField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemListField, value) != true)) {
                    this.ItemListField = value;
                    this.RaisePropertyChanged("ItemList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.ItemType> ItemTypeList {
            get {
                return this.ItemTypeListField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemTypeListField, value) != true)) {
                    this.ItemTypeListField = value;
                    this.RaisePropertyChanged("ItemTypeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.Location> Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.ManPower> ManPowerList {
            get {
                return this.ManPowerListField;
            }
            set {
                if ((object.ReferenceEquals(this.ManPowerListField, value) != true)) {
                    this.ManPowerListField = value;
                    this.RaisePropertyChanged("ManPowerList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gems.UIWPF.evmsService.User Organizer {
            get {
                return this.OrganizerField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizerField, value) != true)) {
                    this.OrganizerField = value;
                    this.RaisePropertyChanged("Organizer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.Participant> ParticipantList {
            get {
                return this.ParticipantListField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipantListField, value) != true)) {
                    this.ParticipantListField = value;
                    this.RaisePropertyChanged("ParticipantList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.Program> ProgramsList {
            get {
                return this.ProgramsListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramsListField, value) != true)) {
                    this.ProgramsListField = value;
                    this.RaisePropertyChanged("ProgramsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDateTime {
            get {
                return this.StartDateTimeField;
            }
            set {
                if ((this.StartDateTimeField.Equals(value) != true)) {
                    this.StartDateTimeField = value;
                    this.RaisePropertyChanged("StartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.Task> TaskList {
            get {
                return this.TaskListField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskListField, value) != true)) {
                    this.TaskListField = value;
                    this.RaisePropertyChanged("TaskList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventContact", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class EventContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Guest", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class Guest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemType", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class ItemType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManPower", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class ManPower : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participant", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class Participant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Program", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class Program : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="evmsService.IEvmsService")]
    public interface IEvmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/login", ReplyAction="http://tempuri.org/IEvmsService/loginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/loginSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.loginResponse login(Gems.UIWPF.evmsService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignLocationAdmin", ReplyAction="http://tempuri.org/IEvmsService/assignLocationAdminResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/assignLocationAdminSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.assignLocationAdminResponse assignLocationAdmin(Gems.UIWPF.evmsService.assignLocationAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignEventOrganizer", ReplyAction="http://tempuri.org/IEvmsService/assignEventOrganizerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/assignEventOrganizerSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.assignEventOrganizerResponse assignEventOrganizer(Gems.UIWPF.evmsService.assignEventOrganizerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignSystemAdmin", ReplyAction="http://tempuri.org/IEvmsService/assignSystemAdminResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/assignSystemAdminSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.assignSystemAdminResponse assignSystemAdmin(Gems.UIWPF.evmsService.assignSystemAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/searchUser", ReplyAction="http://tempuri.org/IEvmsService/searchUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/searchUserSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.searchUserResponse searchUser(Gems.UIWPF.evmsService.searchUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/searchUserByRole", ReplyAction="http://tempuri.org/IEvmsService/searchUserByRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/searchUserByRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.searchUserByRoleResponse searchUserByRole(Gems.UIWPF.evmsService.searchUserByRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/viewUserRole", ReplyAction="http://tempuri.org/IEvmsService/viewUserRoleResponse")]
        Gems.UIWPF.evmsService.viewUserRoleResponse viewUserRole(Gems.UIWPF.evmsService.viewUserRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/CreateEvent", ReplyAction="http://tempuri.org/IEvmsService/CreateEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/CreateEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.CreateEventResponse CreateEvent(Gems.UIWPF.evmsService.CreateEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/ViewEvent", ReplyAction="http://tempuri.org/IEvmsService/ViewEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/ViewEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.ViewEventResponse ViewEvent(Gems.UIWPF.evmsService.ViewEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/EditEvent", ReplyAction="http://tempuri.org/IEvmsService/EditEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/EditEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.EditEventResponse EditEvent(Gems.UIWPF.evmsService.EditEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/DeleteEvent", ReplyAction="http://tempuri.org/IEvmsService/DeleteEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/DeleteEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.DeleteEventResponse DeleteEvent(Gems.UIWPF.evmsService.DeleteEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getNewMessage", ReplyAction="http://tempuri.org/IEvmsService/getNewMessageResponse")]
        Gems.UIWPF.evmsService.getNewMessageResponse getNewMessage(Gems.UIWPF.evmsService.getNewMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getUnreadMessageCount", ReplyAction="http://tempuri.org/IEvmsService/getUnreadMessageCountResponse")]
        Gems.UIWPF.evmsService.getUnreadMessageCountResponse getUnreadMessageCount(Gems.UIWPF.evmsService.getUnreadMessageCountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public loginRequest() {
        }
        
        public loginRequest(string userid, string password) {
            this.userid = userid;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Gems.UIWPF.evmsService.User loginResult;
        
        public loginResponse() {
        }
        
        public loginResponse(Gems.UIWPF.evmsService.User loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="assignLocationAdmin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class assignLocationAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Gems.UIWPF.evmsService.User assigner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string description;
        
        public assignLocationAdminRequest() {
        }
        
        public assignLocationAdminRequest(Gems.UIWPF.evmsService.User assigner, string userid, string description) {
            this.assigner = assigner;
            this.userid = userid;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="assignLocationAdminResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class assignLocationAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool assignLocationAdminResult;
        
        public assignLocationAdminResponse() {
        }
        
        public assignLocationAdminResponse(bool assignLocationAdminResult) {
            this.assignLocationAdminResult = assignLocationAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="assignEventOrganizer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class assignEventOrganizerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Gems.UIWPF.evmsService.User assigner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string description;
        
        public assignEventOrganizerRequest() {
        }
        
        public assignEventOrganizerRequest(Gems.UIWPF.evmsService.User assigner, string userid, string description) {
            this.assigner = assigner;
            this.userid = userid;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="assignEventOrganizerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class assignEventOrganizerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool assignEventOrganizerResult;
        
        public assignEventOrganizerResponse() {
        }
        
        public assignEventOrganizerResponse(bool assignEventOrganizerResult) {
            this.assignEventOrganizerResult = assignEventOrganizerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="assignSystemAdmin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class assignSystemAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Gems.UIWPF.evmsService.User assigner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string description;
        
        public assignSystemAdminRequest() {
        }
        
        public assignSystemAdminRequest(Gems.UIWPF.evmsService.User assigner, string userid, string description) {
            this.assigner = assigner;
            this.userid = userid;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="assignSystemAdminResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class assignSystemAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool assignSystemAdminResult;
        
        public assignSystemAdminResponse() {
        }
        
        public assignSystemAdminResponse(bool assignSystemAdminResult) {
            this.assignSystemAdminResult = assignSystemAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class searchUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userid;
        
        public searchUserRequest() {
        }
        
        public searchUserRequest(string name, string userid) {
            this.name = name;
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class searchUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.User> searchUserResult;
        
        public searchUserResponse() {
        }
        
        public searchUserResponse(System.Collections.Generic.List<Gems.UIWPF.evmsService.User> searchUserResult) {
            this.searchUserResult = searchUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchUserByRole", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class searchUserByRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int r;
        
        public searchUserByRoleRequest() {
        }
        
        public searchUserByRoleRequest(string name, string userid, int r) {
            this.name = name;
            this.userid = userid;
            this.r = r;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchUserByRoleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class searchUserByRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.User> searchUserByRoleResult;
        
        public searchUserByRoleResponse() {
        }
        
        public searchUserByRoleResponse(System.Collections.Generic.List<Gems.UIWPF.evmsService.User> searchUserByRoleResult) {
            this.searchUserByRoleResult = searchUserByRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="viewUserRole", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class viewUserRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userid;
        
        public viewUserRoleRequest() {
        }
        
        public viewUserRoleRequest(string userid) {
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="viewUserRoleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class viewUserRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Gems.UIWPF.evmsService.SysRole viewUserRoleResult;
        
        public viewUserRoleResponse() {
        }
        
        public viewUserRoleResponse(Gems.UIWPF.evmsService.SysRole viewUserRoleResult) {
            this.viewUserRoleResult = viewUserRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateEvent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Gems.UIWPF.evmsService.User u;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string EventName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime EventStartDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime EventEndDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string EventDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string EventWebsite;
        
        public CreateEventRequest() {
        }
        
        public CreateEventRequest(Gems.UIWPF.evmsService.User u, string EventName, System.DateTime EventStartDateTime, System.DateTime EventEndDatetime, string EventDescription, string EventWebsite) {
            this.u = u;
            this.EventName = EventName;
            this.EventStartDateTime = EventStartDateTime;
            this.EventEndDatetime = EventEndDatetime;
            this.EventDescription = EventDescription;
            this.EventWebsite = EventWebsite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateEventResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateEventResponse {
        
        public CreateEventResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ViewEvent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ViewEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Gems.UIWPF.evmsService.User u;
        
        public ViewEventRequest() {
        }
        
        public ViewEventRequest(Gems.UIWPF.evmsService.User u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ViewEventResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ViewEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Gems.UIWPF.evmsService.Event> ViewEventResult;
        
        public ViewEventResponse() {
        }
        
        public ViewEventResponse(System.Collections.Generic.List<Gems.UIWPF.evmsService.Event> ViewEventResult) {
            this.ViewEventResult = ViewEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditEvent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EditEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Gems.UIWPF.evmsService.User u;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Gems.UIWPF.evmsService.Event e;
        
        public EditEventRequest() {
        }
        
        public EditEventRequest(Gems.UIWPF.evmsService.User u, Gems.UIWPF.evmsService.Event e) {
            this.u = u;
            this.e = e;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditEventResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EditEventResponse {
        
        public EditEventResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteEvent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Gems.UIWPF.evmsService.User u;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Gems.UIWPF.evmsService.Event e;
        
        public DeleteEventRequest() {
        }
        
        public DeleteEventRequest(Gems.UIWPF.evmsService.User u, Gems.UIWPF.evmsService.Event e) {
            this.u = u;
            this.e = e;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteEventResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteEventResponse {
        
        public DeleteEventResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getNewMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rid;
        
        public getNewMessageRequest() {
        }
        
        public getNewMessageRequest(string rid) {
            this.rid = rid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNewMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getNewMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string getNewMessageResult;
        
        public getNewMessageResponse() {
        }
        
        public getNewMessageResponse(string getNewMessageResult) {
            this.getNewMessageResult = getNewMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUnreadMessageCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUnreadMessageCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rid;
        
        public getUnreadMessageCountRequest() {
        }
        
        public getUnreadMessageCountRequest(string rid) {
            this.rid = rid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUnreadMessageCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUnreadMessageCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int getUnreadMessageCountResult;
        
        public getUnreadMessageCountResponse() {
        }
        
        public getUnreadMessageCountResponse(int getUnreadMessageCountResult) {
            this.getUnreadMessageCountResult = getUnreadMessageCountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEvmsServiceChannel : Gems.UIWPF.evmsService.IEvmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvmsServiceClient : System.ServiceModel.ClientBase<Gems.UIWPF.evmsService.IEvmsService>, Gems.UIWPF.evmsService.IEvmsService {
        
        public EvmsServiceClient() {
        }
        
        public EvmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gems.UIWPF.evmsService.loginResponse login(Gems.UIWPF.evmsService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public Gems.UIWPF.evmsService.assignLocationAdminResponse assignLocationAdmin(Gems.UIWPF.evmsService.assignLocationAdminRequest request) {
            return base.Channel.assignLocationAdmin(request);
        }
        
        public Gems.UIWPF.evmsService.assignEventOrganizerResponse assignEventOrganizer(Gems.UIWPF.evmsService.assignEventOrganizerRequest request) {
            return base.Channel.assignEventOrganizer(request);
        }
        
        public Gems.UIWPF.evmsService.assignSystemAdminResponse assignSystemAdmin(Gems.UIWPF.evmsService.assignSystemAdminRequest request) {
            return base.Channel.assignSystemAdmin(request);
        }
        
        public Gems.UIWPF.evmsService.searchUserResponse searchUser(Gems.UIWPF.evmsService.searchUserRequest request) {
            return base.Channel.searchUser(request);
        }
        
        public Gems.UIWPF.evmsService.searchUserByRoleResponse searchUserByRole(Gems.UIWPF.evmsService.searchUserByRoleRequest request) {
            return base.Channel.searchUserByRole(request);
        }
        
        public Gems.UIWPF.evmsService.viewUserRoleResponse viewUserRole(Gems.UIWPF.evmsService.viewUserRoleRequest request) {
            return base.Channel.viewUserRole(request);
        }
        
        public Gems.UIWPF.evmsService.CreateEventResponse CreateEvent(Gems.UIWPF.evmsService.CreateEventRequest request) {
            return base.Channel.CreateEvent(request);
        }
        
        public Gems.UIWPF.evmsService.ViewEventResponse ViewEvent(Gems.UIWPF.evmsService.ViewEventRequest request) {
            return base.Channel.ViewEvent(request);
        }
        
        public Gems.UIWPF.evmsService.EditEventResponse EditEvent(Gems.UIWPF.evmsService.EditEventRequest request) {
            return base.Channel.EditEvent(request);
        }
        
        public Gems.UIWPF.evmsService.DeleteEventResponse DeleteEvent(Gems.UIWPF.evmsService.DeleteEventRequest request) {
            return base.Channel.DeleteEvent(request);
        }
        
        public Gems.UIWPF.evmsService.getNewMessageResponse getNewMessage(Gems.UIWPF.evmsService.getNewMessageRequest request) {
            return base.Channel.getNewMessage(request);
        }
        
        public Gems.UIWPF.evmsService.getUnreadMessageCountResponse getUnreadMessageCount(Gems.UIWPF.evmsService.getUnreadMessageCountRequest request) {
            return base.Channel.getUnreadMessageCount(request);
        }
    }
}
