//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gems.UIWPF.evmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gems.UIWPF.evmsService.Faculty UserFacultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isEventOrganizerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isLocationAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isNormalUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSystemAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gems.UIWPF.evmsService.Faculty UserFaculty {
            get {
                return this.UserFacultyField;
            }
            set {
                if ((this.UserFacultyField.Equals(value) != true)) {
                    this.UserFacultyField = value;
                    this.RaisePropertyChanged("UserFaculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isEventOrganizer {
            get {
                return this.isEventOrganizerField;
            }
            set {
                if ((this.isEventOrganizerField.Equals(value) != true)) {
                    this.isEventOrganizerField = value;
                    this.RaisePropertyChanged("isEventOrganizer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isLocationAdmin {
            get {
                return this.isLocationAdminField;
            }
            set {
                if ((this.isLocationAdminField.Equals(value) != true)) {
                    this.isLocationAdminField = value;
                    this.RaisePropertyChanged("isLocationAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isNormalUser {
            get {
                return this.isNormalUserField;
            }
            set {
                if ((this.isNormalUserField.Equals(value) != true)) {
                    this.isNormalUserField = value;
                    this.RaisePropertyChanged("isNormalUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSystemAdmin {
            get {
                return this.isSystemAdminField;
            }
            set {
                if ((this.isSystemAdminField.Equals(value) != true)) {
                    this.isSystemAdminField = value;
                    this.RaisePropertyChanged("isSystemAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                if ((object.ReferenceEquals(this.userIDField, value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Faculty", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public enum Faculty : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Science = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Engineering = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Arts_and_Social_Science = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Dentistry = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Law = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        School_of_Computing = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yong_Loo_Lin_School_of_Medicine = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yong_Siew_Toh_Conservatory_Of_Music = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        School_of_Design_and_Environment = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        School_of_Business = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Centre_for_Development_of_Teaching_and_Learning = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Centre_for_Instructional_Technology = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Computing_Commons = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Education_Resource_Centre = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EduSports = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Khoo_Teck_Puat_Advanced_Surgery_Training_Centre = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lee_Kuan_Yew_School_of_Public_Policy = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PC_Cluster = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Science_Cluster = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UTown = 19,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    [System.SerializableAttribute()]
    public partial class SException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumRoles", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public enum EnumRoles : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System_Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Facility_Admin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Event_Organizer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nil = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gems.UIWPF.evmsService.User OrganizerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizeridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDateTime {
            get {
                return this.EndDateTimeField;
            }
            set {
                if ((this.EndDateTimeField.Equals(value) != true)) {
                    this.EndDateTimeField = value;
                    this.RaisePropertyChanged("EndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gems.UIWPF.evmsService.User Organizer {
            get {
                return this.OrganizerField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizerField, value) != true)) {
                    this.OrganizerField = value;
                    this.RaisePropertyChanged("Organizer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organizerid {
            get {
                return this.OrganizeridField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizeridField, value) != true)) {
                    this.OrganizeridField = value;
                    this.RaisePropertyChanged("Organizerid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDateTime {
            get {
                return this.StartDateTimeField;
            }
            set {
                if ((this.StartDateTimeField.Equals(value) != true)) {
                    this.StartDateTimeField = value;
                    this.RaisePropertyChanged("StartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notifications", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    [System.SerializableAttribute()]
    public partial class Notifications : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isReadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDateTime {
            get {
                return this.SendDateTimeField;
            }
            set {
                if ((this.SendDateTimeField.Equals(value) != true)) {
                    this.SendDateTimeField = value;
                    this.RaisePropertyChanged("SendDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isRead {
            get {
                return this.isReadField;
            }
            set {
                if ((this.isReadField.Equals(value) != true)) {
                    this.isReadField = value;
                    this.RaisePropertyChanged("isRead");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="evmsService.IEvmsService")]
    public interface IEvmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/login", ReplyAction="http://tempuri.org/IEvmsService/loginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/loginSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.User login(string userid, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignLocationAdmin", ReplyAction="http://tempuri.org/IEvmsService/assignLocationAdminResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/assignLocationAdminSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void assignLocationAdmin(Gems.UIWPF.evmsService.User assigner, string userid, Gems.UIWPF.evmsService.Faculty fac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignEventOrganizer", ReplyAction="http://tempuri.org/IEvmsService/assignEventOrganizerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/assignEventOrganizerSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void assignEventOrganizer(Gems.UIWPF.evmsService.User assigner, string userid, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignSystemAdmin", ReplyAction="http://tempuri.org/IEvmsService/assignSystemAdminResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/assignSystemAdminSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void assignSystemAdmin(Gems.UIWPF.evmsService.User assigner, string userid, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/searchUser", ReplyAction="http://tempuri.org/IEvmsService/searchUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/searchUserSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.User[] searchUser(string name, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/searchUserByRole", ReplyAction="http://tempuri.org/IEvmsService/searchUserByRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/searchUserByRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.User[] searchUserByRole(string name, string userid, Gems.UIWPF.evmsService.EnumRoles r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/viewUserRole", ReplyAction="http://tempuri.org/IEvmsService/viewUserRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/viewUserRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.EnumRoles viewUserRole(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/unAssignRole", ReplyAction="http://tempuri.org/IEvmsService/unAssignRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/unAssignRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void unAssignRole(Gems.UIWPF.evmsService.User assigner, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/CreateEvent", ReplyAction="http://tempuri.org/IEvmsService/CreateEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/CreateEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void CreateEvent(Gems.UIWPF.evmsService.User u, string EventName, System.DateTime EventStartDateTime, System.DateTime EventEndDatetime, string EventDescription, string EventWebsite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/ViewEvent", ReplyAction="http://tempuri.org/IEvmsService/ViewEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/ViewEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.Event[] ViewEvent(Gems.UIWPF.evmsService.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/EditEvent", ReplyAction="http://tempuri.org/IEvmsService/EditEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/EditEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void EditEvent(Gems.UIWPF.evmsService.User u, Gems.UIWPF.evmsService.Event e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/DeleteEvent", ReplyAction="http://tempuri.org/IEvmsService/DeleteEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/DeleteEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void DeleteEvent(Gems.UIWPF.evmsService.User u, Gems.UIWPF.evmsService.Event e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getNewMessage", ReplyAction="http://tempuri.org/IEvmsService/getNewMessageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/getNewMessageSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        string getNewMessage(string rid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getUnreadMessageCount", ReplyAction="http://tempuri.org/IEvmsService/getUnreadMessageCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/getUnreadMessageCountSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        int getUnreadMessageCount(string rid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getUnreadMessages", ReplyAction="http://tempuri.org/IEvmsService/getUnreadMessagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/getUnreadMessagesSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.Notifications[] getUnreadMessages(string rid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getAllMessages", ReplyAction="http://tempuri.org/IEvmsService/getAllMessagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/getAllMessagesSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        Gems.UIWPF.evmsService.Notifications[] getAllMessages(string rid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/deleteNotifications", ReplyAction="http://tempuri.org/IEvmsService/deleteNotificationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/deleteNotificationsSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void deleteNotifications(Gems.UIWPF.evmsService.Notifications n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/deleteAllNotificationsOfUser", ReplyAction="http://tempuri.org/IEvmsService/deleteAllNotificationsOfUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/deleteAllNotificationsOfUserSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void deleteAllNotificationsOfUser(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/setNotificationRead", ReplyAction="http://tempuri.org/IEvmsService/setNotificationReadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/setNotificationReadSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void setNotificationRead(Gems.UIWPF.evmsService.Notifications n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/sendNotification", ReplyAction="http://tempuri.org/IEvmsService/sendNotificationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/sendNotificationSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void sendNotification(string sender, string receiver, string title, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/addFacility", ReplyAction="http://tempuri.org/IEvmsService/addFacilityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/addFacilitySExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void addFacility(Gems.UIWPF.evmsService.User u, string LocID, Gems.UIWPF.evmsService.Faculty fac, string loc, string bookingCon, string techCon, int cap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/removeFacility", ReplyAction="http://tempuri.org/IEvmsService/removeFacilityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/removeFacilitySExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void removeFacility(Gems.UIWPF.evmsService.User u, string LocID, Gems.UIWPF.evmsService.Faculty fac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/updateFacility", ReplyAction="http://tempuri.org/IEvmsService/updateFacilityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gems.UIWPF.evmsService.SException), Action="http://tempuri.org/IEvmsService/updateFacilitySExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
        void updateFacility(Gems.UIWPF.evmsService.User u, string locID, Gems.UIWPF.evmsService.Faculty fac, string loc, string bookingCon, string techCon, int cap);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEvmsServiceChannel : Gems.UIWPF.evmsService.IEvmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvmsServiceClient : System.ServiceModel.ClientBase<Gems.UIWPF.evmsService.IEvmsService>, Gems.UIWPF.evmsService.IEvmsService {
        
        public EvmsServiceClient() {
        }
        
        public EvmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gems.UIWPF.evmsService.User login(string userid, string password) {
            return base.Channel.login(userid, password);
        }
        
        public void assignLocationAdmin(Gems.UIWPF.evmsService.User assigner, string userid, Gems.UIWPF.evmsService.Faculty fac) {
            base.Channel.assignLocationAdmin(assigner, userid, fac);
        }
        
        public void assignEventOrganizer(Gems.UIWPF.evmsService.User assigner, string userid, string description) {
            base.Channel.assignEventOrganizer(assigner, userid, description);
        }
        
        public void assignSystemAdmin(Gems.UIWPF.evmsService.User assigner, string userid, string description) {
            base.Channel.assignSystemAdmin(assigner, userid, description);
        }
        
        public Gems.UIWPF.evmsService.User[] searchUser(string name, string userid) {
            return base.Channel.searchUser(name, userid);
        }
        
        public Gems.UIWPF.evmsService.User[] searchUserByRole(string name, string userid, Gems.UIWPF.evmsService.EnumRoles r) {
            return base.Channel.searchUserByRole(name, userid, r);
        }
        
        public Gems.UIWPF.evmsService.EnumRoles viewUserRole(string userid) {
            return base.Channel.viewUserRole(userid);
        }
        
        public void unAssignRole(Gems.UIWPF.evmsService.User assigner, string userid) {
            base.Channel.unAssignRole(assigner, userid);
        }
        
        public void CreateEvent(Gems.UIWPF.evmsService.User u, string EventName, System.DateTime EventStartDateTime, System.DateTime EventEndDatetime, string EventDescription, string EventWebsite) {
            base.Channel.CreateEvent(u, EventName, EventStartDateTime, EventEndDatetime, EventDescription, EventWebsite);
        }
        
        public Gems.UIWPF.evmsService.Event[] ViewEvent(Gems.UIWPF.evmsService.User u) {
            return base.Channel.ViewEvent(u);
        }
        
        public void EditEvent(Gems.UIWPF.evmsService.User u, Gems.UIWPF.evmsService.Event e) {
            base.Channel.EditEvent(u, e);
        }
        
        public void DeleteEvent(Gems.UIWPF.evmsService.User u, Gems.UIWPF.evmsService.Event e) {
            base.Channel.DeleteEvent(u, e);
        }
        
        public string getNewMessage(string rid) {
            return base.Channel.getNewMessage(rid);
        }
        
        public int getUnreadMessageCount(string rid) {
            return base.Channel.getUnreadMessageCount(rid);
        }
        
        public Gems.UIWPF.evmsService.Notifications[] getUnreadMessages(string rid) {
            return base.Channel.getUnreadMessages(rid);
        }
        
        public Gems.UIWPF.evmsService.Notifications[] getAllMessages(string rid) {
            return base.Channel.getAllMessages(rid);
        }
        
        public void deleteNotifications(Gems.UIWPF.evmsService.Notifications n) {
            base.Channel.deleteNotifications(n);
        }
        
        public void deleteAllNotificationsOfUser(string uid) {
            base.Channel.deleteAllNotificationsOfUser(uid);
        }
        
        public void setNotificationRead(Gems.UIWPF.evmsService.Notifications n) {
            base.Channel.setNotificationRead(n);
        }
        
        public void sendNotification(string sender, string receiver, string title, string msg) {
            base.Channel.sendNotification(sender, receiver, title, msg);
        }
        
        public void addFacility(Gems.UIWPF.evmsService.User u, string LocID, Gems.UIWPF.evmsService.Faculty fac, string loc, string bookingCon, string techCon, int cap) {
            base.Channel.addFacility(u, LocID, fac, loc, bookingCon, techCon, cap);
        }
        
        public void removeFacility(Gems.UIWPF.evmsService.User u, string LocID, Gems.UIWPF.evmsService.Faculty fac) {
            base.Channel.removeFacility(u, LocID, fac);
        }
        
        public void updateFacility(Gems.UIWPF.evmsService.User u, string locID, Gems.UIWPF.evmsService.Faculty fac, string loc, string bookingCon, string techCon, int cap) {
            base.Channel.updateFacility(u, locID, fac, loc, bookingCon, techCon, cap);
        }
    }
}
