//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evmsService.entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private string NameField;
        
        private evmsService.entities.Faculty UserFacultyField;
        
        private bool isEventOrganizerField;
        
        private bool isFacilityAdminField;
        
        private bool isNormalUserField;
        
        private bool isSystemAdminField;
        
        private string userIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.Faculty UserFaculty
        {
            get
            {
                return this.UserFacultyField;
            }
            set
            {
                this.UserFacultyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isEventOrganizer
        {
            get
            {
                return this.isEventOrganizerField;
            }
            set
            {
                this.isEventOrganizerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isFacilityAdmin
        {
            get
            {
                return this.isFacilityAdminField;
            }
            set
            {
                this.isFacilityAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isNormalUser
        {
            get
            {
                return this.isNormalUserField;
            }
            set
            {
                this.isNormalUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSystemAdmin
        {
            get
            {
                return this.isSystemAdminField;
            }
            set
            {
                this.isSystemAdminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Faculty", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public enum Faculty : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Science = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Engineering = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Arts_and_Social_Science = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Dentistry = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faculty_of_Law = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        School_of_Computing = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yong_Loo_Lin_School_of_Medicine = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yong_Siew_Toh_Conservatory_Of_Music = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        School_of_Design_and_Environment = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        School_of_Business = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Centre_for_Development_of_Teaching_and_Learning = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Centre_for_Instructional_Technology = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Computing_Commons = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EduSports = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Khoo_Teck_Puat_Advanced_Surgery_Training_Centre = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lee_Kuan_Yew_School_of_Public_Policy = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PC_Cluster = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Science_Cluster = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UTown = 18,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacilityBookingRequest", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class FacilityBookingRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EventIDField;
        
        private evmsService.entities.Faculty FacultyField;
        
        private string RemarksField;
        
        private evmsService.entities.FacilityBookingRequestDetails[] RequestDetailsField;
        
        private System.DateTime RequestEndDateTimeField;
        
        private int RequestIDField;
        
        private System.DateTime RequestStartDateTimeField;
        
        private string RequestorIDField;
        
        private evmsService.entities.BookingStatus StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID
        {
            get
            {
                return this.EventIDField;
            }
            set
            {
                this.EventIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.Faculty Faculty
        {
            get
            {
                return this.FacultyField;
            }
            set
            {
                this.FacultyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.FacilityBookingRequestDetails[] RequestDetails
        {
            get
            {
                return this.RequestDetailsField;
            }
            set
            {
                this.RequestDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestEndDateTime
        {
            get
            {
                return this.RequestEndDateTimeField;
            }
            set
            {
                this.RequestEndDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestID
        {
            get
            {
                return this.RequestIDField;
            }
            set
            {
                this.RequestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestStartDateTime
        {
            get
            {
                return this.RequestStartDateTimeField;
            }
            set
            {
                this.RequestStartDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestorID
        {
            get
            {
                return this.RequestorIDField;
            }
            set
            {
                this.RequestorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.BookingStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacilityBookingRequestDetails", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class FacilityBookingRequestDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EventIDField;
        
        private string FacilityIDField;
        
        private evmsService.entities.Faculty FacultyField;
        
        private int PriorityField;
        
        private int RequestDetailsIDField;
        
        private int RequestidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID
        {
            get
            {
                return this.EventIDField;
            }
            set
            {
                this.EventIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacilityID
        {
            get
            {
                return this.FacilityIDField;
            }
            set
            {
                this.FacilityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.Faculty Faculty
        {
            get
            {
                return this.FacultyField;
            }
            set
            {
                this.FacultyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestDetailsID
        {
            get
            {
                return this.RequestDetailsIDField;
            }
            set
            {
                this.RequestDetailsIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Requestid
        {
            get
            {
                return this.RequestidField;
            }
            set
            {
                this.RequestidField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingStatus", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public enum BookingStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacilityBookingConfirmed", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class FacilityBookingConfirmed : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ConfirmedIDField;
        
        private int EventIDField;
        
        private evmsService.entities.Faculty FacultyField;
        
        private string PurposeField;
        
        private string RemarksField;
        
        private int RequestDetailIDField;
        
        private System.DateTime RequestEndDateTimeField;
        
        private int RequestIDField;
        
        private System.DateTime RequestStartDateTimeField;
        
        private string RequestorIDField;
        
        private string VenueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfirmedID
        {
            get
            {
                return this.ConfirmedIDField;
            }
            set
            {
                this.ConfirmedIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID
        {
            get
            {
                return this.EventIDField;
            }
            set
            {
                this.EventIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.Faculty Faculty
        {
            get
            {
                return this.FacultyField;
            }
            set
            {
                this.FacultyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Purpose
        {
            get
            {
                return this.PurposeField;
            }
            set
            {
                this.PurposeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestDetailID
        {
            get
            {
                return this.RequestDetailIDField;
            }
            set
            {
                this.RequestDetailIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestEndDateTime
        {
            get
            {
                return this.RequestEndDateTimeField;
            }
            set
            {
                this.RequestEndDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestID
        {
            get
            {
                return this.RequestIDField;
            }
            set
            {
                this.RequestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestStartDateTime
        {
            get
            {
                return this.RequestStartDateTimeField;
            }
            set
            {
                this.RequestStartDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestorID
        {
            get
            {
                return this.RequestorIDField;
            }
            set
            {
                this.RequestorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Venue
        {
            get
            {
                return this.VenueField;
            }
            set
            {
                this.VenueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Program", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class Program : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private System.DateTime EndDateTimeField;
        
        private int EventIDField;
        
        private string NameField;
        
        private int ProgramIDField;
        
        private System.DateTime StartDateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDateTime
        {
            get
            {
                return this.EndDateTimeField;
            }
            set
            {
                this.EndDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID
        {
            get
            {
                return this.EventIDField;
            }
            set
            {
                this.EventIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgramID
        {
            get
            {
                return this.ProgramIDField;
            }
            set
            {
                this.ProgramIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDateTime
        {
            get
            {
                return this.StartDateTimeField;
            }
            set
            {
                this.StartDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Right", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class Right : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FunctionEnumField;
        
        private int RoleIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FunctionEnum
        {
            get
            {
                return this.FunctionEnumField;
            }
            set
            {
                this.FunctionEnumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID
        {
            get
            {
                return this.RoleIDField;
            }
            set
            {
                this.RoleIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Guest", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class Guest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContactField;
        
        private string DescriptionField;
        
        private int EventIDField;
        
        private int GuestIdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact
        {
            get
            {
                return this.ContactField;
            }
            set
            {
                this.ContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID
        {
            get
            {
                return this.EventIDField;
            }
            set
            {
                this.EventIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GuestId
        {
            get
            {
                return this.GuestIdField;
            }
            set
            {
                this.GuestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Facility", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class Facility : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BookingContactField;
        
        private int CapacityField;
        
        private string FacilityIDField;
        
        private evmsService.entities.Faculty FacultyField;
        
        private string LocationField;
        
        private string TechContactField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingContact
        {
            get
            {
                return this.BookingContactField;
            }
            set
            {
                this.BookingContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacity
        {
            get
            {
                return this.CapacityField;
            }
            set
            {
                this.CapacityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacilityID
        {
            get
            {
                return this.FacilityIDField;
            }
            set
            {
                this.FacilityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.Faculty Faculty
        {
            get
            {
                return this.FacultyField;
            }
            set
            {
                this.FacultyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechContact
        {
            get
            {
                return this.TechContactField;
            }
            set
            {
                this.TechContactField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private System.DateTime EndDateTimeField;
        
        private int EventIDField;
        
        private string NameField;
        
        private evmsService.entities.User OrganizerField;
        
        private string OrganizeridField;
        
        private System.DateTime StartDateTimeField;
        
        private string WebsiteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDateTime
        {
            get
            {
                return this.EndDateTimeField;
            }
            set
            {
                this.EndDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID
        {
            get
            {
                return this.EventIDField;
            }
            set
            {
                this.EventIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public evmsService.entities.User Organizer
        {
            get
            {
                return this.OrganizerField;
            }
            set
            {
                this.OrganizerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organizerid
        {
            get
            {
                return this.OrganizeridField;
            }
            set
            {
                this.OrganizeridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDateTime
        {
            get
            {
                return this.StartDateTimeField;
            }
            set
            {
                this.StartDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website
        {
            get
            {
                return this.WebsiteField;
            }
            set
            {
                this.WebsiteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumRoles", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public enum EnumRoles : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System_Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Facility_Admin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Event_Organizer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nil = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notifications", Namespace="http://schemas.datacontract.org/2004/07/evmsService.entities")]
    public partial class Notifications : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string ReceiverField;
        
        private System.DateTime SendDateTimeField;
        
        private string SenderField;
        
        private string TitleField;
        
        private bool isReadField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receiver
        {
            get
            {
                return this.ReceiverField;
            }
            set
            {
                this.ReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDateTime
        {
            get
            {
                return this.SendDateTimeField;
            }
            set
            {
                this.SendDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isRead
        {
            get
            {
                return this.isReadField;
            }
            set
            {
                this.isReadField = value;
            }
        }
    }
}
namespace evmsService.Controllers
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    public partial class SException : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEvmsService")]
public interface IEvmsService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/cancelFacilityBooking", ReplyAction="http://tempuri.org/IEvmsService/cancelFacilityBookingResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/cancelFacilityBookingSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void cancelFacilityBooking(evmsService.entities.User user, int reqID, int evID, string remarks);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/viewFacilityBookingRequests", ReplyAction="http://tempuri.org/IEvmsService/viewFacilityBookingRequestsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/viewFacilityBookingRequestsSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.FacilityBookingRequest[] viewFacilityBookingRequests(evmsService.entities.User user, int evID, int status, bool viewAllStatus, bool viewAllEvents);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getActivitiesForDay", ReplyAction="http://tempuri.org/IEvmsService/getActivitiesForDayResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getActivitiesForDaySExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.FacilityBookingConfirmed[] getActivitiesForDay(evmsService.entities.User u, System.DateTime day, evmsService.entities.Faculty faculty, string venue);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getConfirmedBooking", ReplyAction="http://tempuri.org/IEvmsService/getConfirmedBookingResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getConfirmedBookingSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.FacilityBookingConfirmed getConfirmedBooking(int reqID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getItemsTypes", ReplyAction="http://tempuri.org/IEvmsService/getItemsTypesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getItemsTypesSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    string[] getItemsTypes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/addItemsTypes", ReplyAction="http://tempuri.org/IEvmsService/addItemsTypesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/addItemsTypesSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void addItemsTypes(string itemType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/updateItemTypes", ReplyAction="http://tempuri.org/IEvmsService/updateItemTypesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/updateItemTypesSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void updateItemTypes(string itemType, string newItemType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/deleteItemType", ReplyAction="http://tempuri.org/IEvmsService/deleteItemTypeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/deleteItemTypeSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void deleteItemType(string itemType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/ViewProgram", ReplyAction="http://tempuri.org/IEvmsService/ViewProgramResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/ViewProgramSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Program[] ViewProgram(evmsService.entities.User u, int EventID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/EditProgram", ReplyAction="http://tempuri.org/IEvmsService/EditProgramResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/EditProgramSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void EditProgram(evmsService.entities.User u, int ProgramID, string ProgramName, System.DateTime ProgramStartDateTime, System.DateTime ProgramEndDatetime, string ProgramDescription);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/DeleteProgram", ReplyAction="http://tempuri.org/IEvmsService/DeleteProgramResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/DeleteProgramSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void DeleteProgram(evmsService.entities.User u, int ProgramID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/AddRole", ReplyAction="http://tempuri.org/IEvmsService/AddRoleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/AddRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    int AddRole(evmsService.entities.User u, string RoleUserID, int EventID, string RolePost, string RoleDescription, int[] functionID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/DeleteRole", ReplyAction="http://tempuri.org/IEvmsService/DeleteRoleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/DeleteRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void DeleteRole(evmsService.entities.User u, int RoleID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/EditRights", ReplyAction="http://tempuri.org/IEvmsService/EditRightsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/EditRightsSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void EditRights(evmsService.entities.User u, string RoleUserID, int RoleID, string RolePost, string RoleDescription, int[] functionID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/GetRights", ReplyAction="http://tempuri.org/IEvmsService/GetRightsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/GetRightsSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Right[] GetRights(int EventID, string UserID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/AddGuest", ReplyAction="http://tempuri.org/IEvmsService/AddGuestResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/AddGuestSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    int AddGuest(evmsService.entities.User u, int EventID, string GuestName, string GuestContact, string GuestDescription);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/ViewGuest", ReplyAction="http://tempuri.org/IEvmsService/ViewGuestResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/ViewGuestSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Guest[] ViewGuest(evmsService.entities.User u, int EventID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/EditGuest", ReplyAction="http://tempuri.org/IEvmsService/EditGuestResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/EditGuestSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void EditGuest(evmsService.entities.User u, int GuestID, string GuestName, string GuestDescription, string GuestContact);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/DeleteGuest", ReplyAction="http://tempuri.org/IEvmsService/DeleteGuestResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/DeleteGuestSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void DeleteGuest(evmsService.entities.User u, int GuestID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/removeFacility", ReplyAction="http://tempuri.org/IEvmsService/removeFacilityResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/removeFacilitySExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void removeFacility(evmsService.entities.User u, string venue, evmsService.entities.Faculty fac);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/updateFacility", ReplyAction="http://tempuri.org/IEvmsService/updateFacilityResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/updateFacilitySExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void updateFacility(evmsService.entities.User u, string venue, evmsService.entities.Faculty fac, string loc, string bookingCon, string techCon, int cap);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getFacilityAdmin", ReplyAction="http://tempuri.org/IEvmsService/getFacilityAdminResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getFacilityAdminSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Faculty getFacilityAdmin(string userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getFacilityAdminFaculty", ReplyAction="http://tempuri.org/IEvmsService/getFacilityAdminFacultyResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getFacilityAdminFacultySExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    string getFacilityAdminFaculty(evmsService.entities.Faculty userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getFacilityAdmins", ReplyAction="http://tempuri.org/IEvmsService/getFacilityAdminsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getFacilityAdminsSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.User[] getFacilityAdmins();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getVenuesByFaculty", ReplyAction="http://tempuri.org/IEvmsService/getVenuesByFacultyResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getVenuesByFacultySExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Facility[] getVenuesByFaculty(evmsService.entities.Faculty f, int minCap, int maxCap);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getVenues", ReplyAction="http://tempuri.org/IEvmsService/getVenuesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getVenuesSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Facility[] getVenues(int minCap, int maxCap);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getVenuesByCap", ReplyAction="http://tempuri.org/IEvmsService/getVenuesByCapResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getVenuesByCapSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Facility[] getVenuesByCap(evmsService.entities.Faculty fac, string faciID, int minCap, int maxCap);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/addFacilityBookingRequest", ReplyAction="http://tempuri.org/IEvmsService/addFacilityBookingRequestResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/addFacilityBookingRequestSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    bool addFacilityBookingRequest(evmsService.entities.User u, evmsService.entities.Event e, evmsService.entities.Faculty faculty, System.DateTime reqstart, System.DateTime reqEnd, evmsService.entities.FacilityBookingRequestDetails[] reqDetails);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/checkRequestExist", ReplyAction="http://tempuri.org/IEvmsService/checkRequestExistResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/checkRequestExistSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    bool checkRequestExist(int eventid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getFacBookingRequestList", ReplyAction="http://tempuri.org/IEvmsService/getFacBookingRequestListResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getFacBookingRequestListSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.FacilityBookingRequest[] getFacBookingRequestList(evmsService.entities.User FacAdmin);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/approveFacilityBooking", ReplyAction="http://tempuri.org/IEvmsService/approveFacilityBookingResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/approveFacilityBookingSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void approveFacilityBooking(evmsService.entities.User approver, int reqID, int evID, int reqDetailID, string remarks, string purpose);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/rejectFacilityBooking", ReplyAction="http://tempuri.org/IEvmsService/rejectFacilityBookingResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/rejectFacilityBookingSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void rejectFacilityBooking(evmsService.entities.User rejecter, int reqID, int evID, string remarks);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/dropConfirmedRequest", ReplyAction="http://tempuri.org/IEvmsService/dropConfirmedRequestResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/dropConfirmedRequestSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void dropConfirmedRequest(evmsService.entities.User u, int reqID, int evID, string remarks);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/login", ReplyAction="http://tempuri.org/IEvmsService/loginResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/loginSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.User login(string userid, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignLocationAdmin", ReplyAction="http://tempuri.org/IEvmsService/assignLocationAdminResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/assignLocationAdminSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void assignLocationAdmin(evmsService.entities.User assigner, string userid, evmsService.entities.Faculty fac);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignEventOrganizer", ReplyAction="http://tempuri.org/IEvmsService/assignEventOrganizerResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/assignEventOrganizerSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void assignEventOrganizer(evmsService.entities.User assigner, string userid, string description);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/assignSystemAdmin", ReplyAction="http://tempuri.org/IEvmsService/assignSystemAdminResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/assignSystemAdminSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void assignSystemAdmin(evmsService.entities.User assigner, string userid, string description);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/searchUser", ReplyAction="http://tempuri.org/IEvmsService/searchUserResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/searchUserSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.User[] searchUser(string name, string userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/searchUserByRole", ReplyAction="http://tempuri.org/IEvmsService/searchUserByRoleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/searchUserByRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.User[] searchUserByRole(string name, string userid, evmsService.entities.EnumRoles r);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/viewUserRole", ReplyAction="http://tempuri.org/IEvmsService/viewUserRoleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/viewUserRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.EnumRoles viewUserRole(string userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/unAssignRole", ReplyAction="http://tempuri.org/IEvmsService/unAssignRoleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/unAssignRoleSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void unAssignRole(evmsService.entities.User assigner, string userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getUserName", ReplyAction="http://tempuri.org/IEvmsService/getUserNameResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getUserNameSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    string getUserName(string userid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getNewMessage", ReplyAction="http://tempuri.org/IEvmsService/getNewMessageResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getNewMessageSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    string getNewMessage(string rid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getUnreadMessageCount", ReplyAction="http://tempuri.org/IEvmsService/getUnreadMessageCountResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getUnreadMessageCountSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    int getUnreadMessageCount(string rid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getUnreadMessages", ReplyAction="http://tempuri.org/IEvmsService/getUnreadMessagesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getUnreadMessagesSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Notifications[] getUnreadMessages(string rid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getAllMessages", ReplyAction="http://tempuri.org/IEvmsService/getAllMessagesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getAllMessagesSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Notifications[] getAllMessages(string rid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/deleteNotifications", ReplyAction="http://tempuri.org/IEvmsService/deleteNotificationsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/deleteNotificationsSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void deleteNotifications(evmsService.entities.Notifications n);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/deleteAllNotificationsOfUser", ReplyAction="http://tempuri.org/IEvmsService/deleteAllNotificationsOfUserResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/deleteAllNotificationsOfUserSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void deleteAllNotificationsOfUser(string uid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/setNotificationRead", ReplyAction="http://tempuri.org/IEvmsService/setNotificationReadResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/setNotificationReadSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void setNotificationRead(evmsService.entities.Notifications n);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/sendNotification", ReplyAction="http://tempuri.org/IEvmsService/sendNotificationResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/sendNotificationSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void sendNotification(string sender, string receiver, string title, string msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/CreateEvent", ReplyAction="http://tempuri.org/IEvmsService/CreateEventResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/CreateEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    int CreateEvent(evmsService.entities.User u, string EventName, System.DateTime EventStartDateTime, System.DateTime EventEndDatetime, string EventDescription, string EventWebsite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/ViewEvent", ReplyAction="http://tempuri.org/IEvmsService/ViewEventResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/ViewEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Event[] ViewEvent(evmsService.entities.User u);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/EditEvent", ReplyAction="http://tempuri.org/IEvmsService/EditEventResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/EditEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void EditEvent(evmsService.entities.User u, evmsService.entities.Event e, string EventOrganizerID, string EventName, System.DateTime EventStartDateTime, System.DateTime EventEndDatetime, string EventDescription, string EventWebsite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/DeleteEvent", ReplyAction="http://tempuri.org/IEvmsService/DeleteEventResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/DeleteEventSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    void DeleteEvent(evmsService.entities.User u, evmsService.entities.Event e);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/viewEventsbyDate", ReplyAction="http://tempuri.org/IEvmsService/viewEventsbyDateResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/viewEventsbyDateSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Event[] viewEventsbyDate(evmsService.entities.User u, System.DateTime start, System.DateTime end);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/getEventName", ReplyAction="http://tempuri.org/IEvmsService/getEventNameResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/getEventNameSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    string getEventName(int eventid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/viewAllEvents", ReplyAction="http://tempuri.org/IEvmsService/viewAllEventsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/viewAllEventsSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    evmsService.entities.Event[] viewAllEvents(evmsService.entities.User u);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvmsService/AddProgram", ReplyAction="http://tempuri.org/IEvmsService/AddProgramResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(evmsService.Controllers.SException), Action="http://tempuri.org/IEvmsService/AddProgramSExceptionFault", Name="SException", Namespace="http://schemas.datacontract.org/2004/07/evmsService.Controllers")]
    int AddProgram(evmsService.entities.User u, string ProgramName, System.DateTime ProgramStartDateTime, System.DateTime ProgramEndDatetime, string ProgramDescription, int ProgramEventID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEvmsServiceChannel : IEvmsService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EvmsServiceClient : System.ServiceModel.ClientBase<IEvmsService>, IEvmsService
{
    
    public EvmsServiceClient()
    {
    }
    
    public EvmsServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EvmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EvmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EvmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void cancelFacilityBooking(evmsService.entities.User user, int reqID, int evID, string remarks)
    {
        base.Channel.cancelFacilityBooking(user, reqID, evID, remarks);
    }
    
    public evmsService.entities.FacilityBookingRequest[] viewFacilityBookingRequests(evmsService.entities.User user, int evID, int status, bool viewAllStatus, bool viewAllEvents)
    {
        return base.Channel.viewFacilityBookingRequests(user, evID, status, viewAllStatus, viewAllEvents);
    }
    
    public evmsService.entities.FacilityBookingConfirmed[] getActivitiesForDay(evmsService.entities.User u, System.DateTime day, evmsService.entities.Faculty faculty, string venue)
    {
        return base.Channel.getActivitiesForDay(u, day, faculty, venue);
    }
    
    public evmsService.entities.FacilityBookingConfirmed getConfirmedBooking(int reqID)
    {
        return base.Channel.getConfirmedBooking(reqID);
    }
    
    public string[] getItemsTypes()
    {
        return base.Channel.getItemsTypes();
    }
    
    public void addItemsTypes(string itemType)
    {
        base.Channel.addItemsTypes(itemType);
    }
    
    public void updateItemTypes(string itemType, string newItemType)
    {
        base.Channel.updateItemTypes(itemType, newItemType);
    }
    
    public void deleteItemType(string itemType)
    {
        base.Channel.deleteItemType(itemType);
    }
    
    public evmsService.entities.Program[] ViewProgram(evmsService.entities.User u, int EventID)
    {
        return base.Channel.ViewProgram(u, EventID);
    }
    
    public void EditProgram(evmsService.entities.User u, int ProgramID, string ProgramName, System.DateTime ProgramStartDateTime, System.DateTime ProgramEndDatetime, string ProgramDescription)
    {
        base.Channel.EditProgram(u, ProgramID, ProgramName, ProgramStartDateTime, ProgramEndDatetime, ProgramDescription);
    }
    
    public void DeleteProgram(evmsService.entities.User u, int ProgramID)
    {
        base.Channel.DeleteProgram(u, ProgramID);
    }
    
    public int AddRole(evmsService.entities.User u, string RoleUserID, int EventID, string RolePost, string RoleDescription, int[] functionID)
    {
        return base.Channel.AddRole(u, RoleUserID, EventID, RolePost, RoleDescription, functionID);
    }
    
    public void DeleteRole(evmsService.entities.User u, int RoleID)
    {
        base.Channel.DeleteRole(u, RoleID);
    }
    
    public void EditRights(evmsService.entities.User u, string RoleUserID, int RoleID, string RolePost, string RoleDescription, int[] functionID)
    {
        base.Channel.EditRights(u, RoleUserID, RoleID, RolePost, RoleDescription, functionID);
    }
    
    public evmsService.entities.Right[] GetRights(int EventID, string UserID)
    {
        return base.Channel.GetRights(EventID, UserID);
    }
    
    public int AddGuest(evmsService.entities.User u, int EventID, string GuestName, string GuestContact, string GuestDescription)
    {
        return base.Channel.AddGuest(u, EventID, GuestName, GuestContact, GuestDescription);
    }
    
    public evmsService.entities.Guest[] ViewGuest(evmsService.entities.User u, int EventID)
    {
        return base.Channel.ViewGuest(u, EventID);
    }
    
    public void EditGuest(evmsService.entities.User u, int GuestID, string GuestName, string GuestDescription, string GuestContact)
    {
        base.Channel.EditGuest(u, GuestID, GuestName, GuestDescription, GuestContact);
    }
    
    public void DeleteGuest(evmsService.entities.User u, int GuestID)
    {
        base.Channel.DeleteGuest(u, GuestID);
    }
    
    public void removeFacility(evmsService.entities.User u, string venue, evmsService.entities.Faculty fac)
    {
        base.Channel.removeFacility(u, venue, fac);
    }
    
    public void updateFacility(evmsService.entities.User u, string venue, evmsService.entities.Faculty fac, string loc, string bookingCon, string techCon, int cap)
    {
        base.Channel.updateFacility(u, venue, fac, loc, bookingCon, techCon, cap);
    }
    
    public evmsService.entities.Faculty getFacilityAdmin(string userid)
    {
        return base.Channel.getFacilityAdmin(userid);
    }
    
    public string getFacilityAdminFaculty(evmsService.entities.Faculty userid)
    {
        return base.Channel.getFacilityAdminFaculty(userid);
    }
    
    public evmsService.entities.User[] getFacilityAdmins()
    {
        return base.Channel.getFacilityAdmins();
    }
    
    public evmsService.entities.Facility[] getVenuesByFaculty(evmsService.entities.Faculty f, int minCap, int maxCap)
    {
        return base.Channel.getVenuesByFaculty(f, minCap, maxCap);
    }
    
    public evmsService.entities.Facility[] getVenues(int minCap, int maxCap)
    {
        return base.Channel.getVenues(minCap, maxCap);
    }
    
    public evmsService.entities.Facility[] getVenuesByCap(evmsService.entities.Faculty fac, string faciID, int minCap, int maxCap)
    {
        return base.Channel.getVenuesByCap(fac, faciID, minCap, maxCap);
    }
    
    public bool addFacilityBookingRequest(evmsService.entities.User u, evmsService.entities.Event e, evmsService.entities.Faculty faculty, System.DateTime reqstart, System.DateTime reqEnd, evmsService.entities.FacilityBookingRequestDetails[] reqDetails)
    {
        return base.Channel.addFacilityBookingRequest(u, e, faculty, reqstart, reqEnd, reqDetails);
    }
    
    public bool checkRequestExist(int eventid)
    {
        return base.Channel.checkRequestExist(eventid);
    }
    
    public evmsService.entities.FacilityBookingRequest[] getFacBookingRequestList(evmsService.entities.User FacAdmin)
    {
        return base.Channel.getFacBookingRequestList(FacAdmin);
    }
    
    public void approveFacilityBooking(evmsService.entities.User approver, int reqID, int evID, int reqDetailID, string remarks, string purpose)
    {
        base.Channel.approveFacilityBooking(approver, reqID, evID, reqDetailID, remarks, purpose);
    }
    
    public void rejectFacilityBooking(evmsService.entities.User rejecter, int reqID, int evID, string remarks)
    {
        base.Channel.rejectFacilityBooking(rejecter, reqID, evID, remarks);
    }
    
    public void dropConfirmedRequest(evmsService.entities.User u, int reqID, int evID, string remarks)
    {
        base.Channel.dropConfirmedRequest(u, reqID, evID, remarks);
    }
    
    public evmsService.entities.User login(string userid, string password)
    {
        return base.Channel.login(userid, password);
    }
    
    public void assignLocationAdmin(evmsService.entities.User assigner, string userid, evmsService.entities.Faculty fac)
    {
        base.Channel.assignLocationAdmin(assigner, userid, fac);
    }
    
    public void assignEventOrganizer(evmsService.entities.User assigner, string userid, string description)
    {
        base.Channel.assignEventOrganizer(assigner, userid, description);
    }
    
    public void assignSystemAdmin(evmsService.entities.User assigner, string userid, string description)
    {
        base.Channel.assignSystemAdmin(assigner, userid, description);
    }
    
    public evmsService.entities.User[] searchUser(string name, string userid)
    {
        return base.Channel.searchUser(name, userid);
    }
    
    public evmsService.entities.User[] searchUserByRole(string name, string userid, evmsService.entities.EnumRoles r)
    {
        return base.Channel.searchUserByRole(name, userid, r);
    }
    
    public evmsService.entities.EnumRoles viewUserRole(string userid)
    {
        return base.Channel.viewUserRole(userid);
    }
    
    public void unAssignRole(evmsService.entities.User assigner, string userid)
    {
        base.Channel.unAssignRole(assigner, userid);
    }
    
    public string getUserName(string userid)
    {
        return base.Channel.getUserName(userid);
    }
    
    public string getNewMessage(string rid)
    {
        return base.Channel.getNewMessage(rid);
    }
    
    public int getUnreadMessageCount(string rid)
    {
        return base.Channel.getUnreadMessageCount(rid);
    }
    
    public evmsService.entities.Notifications[] getUnreadMessages(string rid)
    {
        return base.Channel.getUnreadMessages(rid);
    }
    
    public evmsService.entities.Notifications[] getAllMessages(string rid)
    {
        return base.Channel.getAllMessages(rid);
    }
    
    public void deleteNotifications(evmsService.entities.Notifications n)
    {
        base.Channel.deleteNotifications(n);
    }
    
    public void deleteAllNotificationsOfUser(string uid)
    {
        base.Channel.deleteAllNotificationsOfUser(uid);
    }
    
    public void setNotificationRead(evmsService.entities.Notifications n)
    {
        base.Channel.setNotificationRead(n);
    }
    
    public void sendNotification(string sender, string receiver, string title, string msg)
    {
        base.Channel.sendNotification(sender, receiver, title, msg);
    }
    
    public int CreateEvent(evmsService.entities.User u, string EventName, System.DateTime EventStartDateTime, System.DateTime EventEndDatetime, string EventDescription, string EventWebsite)
    {
        return base.Channel.CreateEvent(u, EventName, EventStartDateTime, EventEndDatetime, EventDescription, EventWebsite);
    }
    
    public evmsService.entities.Event[] ViewEvent(evmsService.entities.User u)
    {
        return base.Channel.ViewEvent(u);
    }
    
    public void EditEvent(evmsService.entities.User u, evmsService.entities.Event e, string EventOrganizerID, string EventName, System.DateTime EventStartDateTime, System.DateTime EventEndDatetime, string EventDescription, string EventWebsite)
    {
        base.Channel.EditEvent(u, e, EventOrganizerID, EventName, EventStartDateTime, EventEndDatetime, EventDescription, EventWebsite);
    }
    
    public void DeleteEvent(evmsService.entities.User u, evmsService.entities.Event e)
    {
        base.Channel.DeleteEvent(u, e);
    }
    
    public evmsService.entities.Event[] viewEventsbyDate(evmsService.entities.User u, System.DateTime start, System.DateTime end)
    {
        return base.Channel.viewEventsbyDate(u, start, end);
    }
    
    public string getEventName(int eventid)
    {
        return base.Channel.getEventName(eventid);
    }
    
    public evmsService.entities.Event[] viewAllEvents(evmsService.entities.User u)
    {
        return base.Channel.viewAllEvents(u);
    }
    
    public int AddProgram(evmsService.entities.User u, string ProgramName, System.DateTime ProgramStartDateTime, System.DateTime ProgramEndDatetime, string ProgramDescription, int ProgramEventID)
    {
        return base.Channel.AddProgram(u, ProgramName, ProgramStartDateTime, ProgramEndDatetime, ProgramDescription, ProgramEventID);
    }
}
